// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webApi.Data;

namespace webApi.Migrations
{
    [DbContext(typeof(SelectCrsContext))]
    [Migration("20201110081249_Create")]
    partial class Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("webApi.Models.Course", b =>
                {
                    b.Property<string>("Stu_ID")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("CrsName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Crs_Seq")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Timestamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Stu_ID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("webApi.Models.Student", b =>
                {
                    b.Property<string>("Stu_ID")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Stu_Seq")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Tch_ID")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Stu_ID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("webApi.Models.Teacher", b =>
                {
                    b.Property<string>("Tch_ID")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Major")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Tch_Seq")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Timestamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Tch_ID");

                    b.ToTable("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
